const ShopTypesActions = {
  SET_COLLECTION_DATA: "SET_COLLECTION_DATA",
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_SUCCESS"
};

export default ShopTypesActions;
