export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  ADD_ALL: "ADD_ALL",
  CLEAR_ITEMS_FROM_CART: "CLEAR_ITEMS_FROM_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_CART_START: "CLEAR_CART_START",
  CLEAR_CART_SUCCESS: "CLEAR_CART_SUCCESS",
  CLEAR_CART_FAILURE: "CLEAR_CART_FAILURE",
};
